# -*- coding: utf-8 -*-
"""bookstore_clerk

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0Ijs00xw6a08Qn-Gcu-2546bJIzYsAG
"""

# import SQLite functions
import sqlite3

#creating the database
database = sqlite3.connect('ebookstore_db')
cursor = database.cursor() #Get a cursor object

cursor.execute('''
                CREATE TABLE IF NOT EXISTS books(id INTEGER, title TEXT, author TEXT, qty INTEGER)
                ''')
print('database created')
database.commit()

# adding data into the table
id = 3001
title = 'A Tale of Two Cities'
author = 'Charles Dickens'
qty = 30

cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))
database.commit()

id = 3002
title = 'Harry Potter and the Philosophers Stone'
author = 'J.K Rowling'
qty = 40

cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))

database.commit()

id = 3003
title = 'The Lion the Witch and the Wardrobe'
author = 'CS Lewis'
qty = 25

cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))

database.commit()

id = 3004
title = 'The Lord of the rings'
author = 'JRR Tolkien'
qty = 37

cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))

database.commit()

id = 3005
title = 'Alice in Wonderland'
author = 'Lewis Carroll'
qty = 12

cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))

database.commit()

# creating functions for more efficient program functionality

# add book function
def add_book():

    id = int(input("Enter the book ID here: "))
    title = input("Enter the book Title here: ")
    author = input("Enter the book Author here: ")
    qty = int(input("Enter the book quantity here: "))

    cursor.execute(''' 
                INSERT INTO books VALUES(?,?,?,?)
                ''', (id, title, author, qty))
    
    print('New book added successfully')

    database.commit()

# search for a book function
def book_search():
    
    search_attribute = input('''Would you prefer to search for the desired book by ID, Author or Title? 
    (type: id/author/title , depending on your choice): ''').lower()
    if search_attribute == 'id':
        id_check = input("Enter the ID of the book here: ")
        cursor.execute('''
                    SELECT * FROM books WHERE id=?
                    ''', (id_check,))
    
        book_info = cursor.fetchone()
        print(book_info)
    
    elif search_attribute == 'author':
        author_check = input("Enter the Author of the book you are looking for here: ")
        cursor.execute('''
                    SELECT * FROM books WHERE author=?
                    ''', (author_check,))
    
        book_info = cursor.fetchone()
        print(book_info)

    elif search_attribute == 'title':
        title_check = input("Enter the Author of the book you are looking for here: ")
        cursor.execute('''
                    SELECT * FROM books WHERE title=?
                    ''', (title_check,))
    
        book_info = cursor.fetchone()
        print(book_info)

    else:
        print("Invalid Input.")

# update book function
def update_book():

    # fetch all data
    cursor.execute(''' 
                SELECT * FROM books
                ''')

    all_data = cursor.fetchall()
    print(all_data)

    id_choice = int(input("Please enter the book ID you want to change here: "))

    edit_selection = input('''What would you like to change?Title, Author or Quantity? 
    (type: id/title/author/qty , depending on your choice): ''').lower()


    if edit_selection == 'title':

        new_title = input("Enter the new book title here: ")

        cursor.execute('''
                        UPDATE books SET title=? WHERE id=?
                        ''', (new_title, id_choice,))
        
        print("Entry successfully updated!")
        database.commit()
    
    if edit_selection == 'author':

        new_author = input("Enter the new book author here: ")

        cursor.execute('''
                        UPDATE books SET author=? WHERE id=?
                        ''', (new_author, id_choice,))
        
        print("Entry successfully updated!")
        database.commit()
    
    if edit_selection == 'qty':

        new_qty = input("Enter the new book qty here: ")

        cursor.execute('''
                        UPDATE books SET qty=? WHERE id=?
                        ''', (new_qty, id_choice,))
        
        print("Entry successfully updated!")
        database.commit()

# delete book function
def delete_book():

    id_delete = int(input("Enter the id of the book here: "))

    cursor.execute('''
                    DELETE FROM books WHERE id=?
                    ''', (id_delete,))
    
    print("Entry successfully removed")
    database.commit()


while True:
    # presenting the menu to the user and 
    # making sure that the user input is converted to lower case.
    print()
    menu = input('''Select one of the following Options below:
1. Enter book
2. Update book
3. Delete book
4. Search books
0. Exit
: ''').lower()

    if menu == '1':
        print(add_book())
    elif menu == '2':
        print(update_book())
    elif menu == '3':
        print(delete_book())
    elif menu == '4':
        print(book_search())
    elif menu == '0':
        database.close()
        print('Connection to database closed. Goodatabaseye!')
    else:
        print("You have made a wrong choice, Please try again")